spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: '0121'
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: city-provider-1
logging:
  level:
    root: INFO
info.app.name: provider
info.company.name: example
info.author.name: demo